CREATE TABLE IF NOT EXISTS public.users
(
    id UUID PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    role VARCHAR(50) NOT NULL,
    hash_password VARCHAR(255) NOT NULL,
    is_blocked BOOLEAN NOT NULL DEFAULT FALSE,
    account_create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
